### ISSUE TITLE
iOS (APNS) Examples?

### ISSUE THREAD

**Issue by bcooper** [patientslikeme/firebase_cloud_messenger#14]
This is working excellent for pushing to Android following your example.  But I cannot get the APNS or iOS combination of values and configuration to work.  Do you have any APNS examples that you could provide?

**Comment by vincedevendra** [comment]
@bcooper I'll do some work to update the Readme in the next few days, but in the meantime, here's a sample APNS message hash from another Issue:

```ruby

message = {
  apns: {
    payload: {
     aps: {
       alert: {
         title: "title"
       },
       badge: 2 }
     }
  },
  token: "my_fcm_reg_id"
}
```

You can see all the supported fields in the different data objects like `FirebaseCloudMessenger::Apns::ApsDictionary`, which mirror Apple's own APNS docs.

**Comment by bcooper** [comment]
Thanks for the quick response and info.  Just that input helped me understand how the payload fits in.

**Comment by vincedevendra** [comment]
Glad I could help! Yeah, the JSON structure that the FCM API expects for APNS messages is a bit oddly constructed, imo, but I think it's best to keep the wrapper light and match that structure. We'll just have to do some documentation work so folks can more easily see what that structure is.

**Comment by bcooper** [comment]
I will close this issue. APNS notifications working. Thanks for the help and for creating this Gem.
