### ISSUE TITLE
Nested objects inside of the data attribute on payload

### ISSUE THREAD

**Issue by pablomarti** [patientslikeme/firebase_cloud_messenger#15]
Hi.

Is it possible to send custom payloads inside of the `data` attribute? For example, nested objects? I am trying to send some nested objects inside of the `data` attribute and I am getting the following errors: 

Message: Invalid JSON payload received. Unknown name "metadata" at 'message.android.data[3].value': Cannot find field.

Thank you.

**Comment by vincedevendra** [comment]
Hello!

According to Google's [spec](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages), it can contain custom payloads, in the sense that the `data` object can contain whatever keys you want, but the values can only be strings. Hope that helps!

**Comment by pablomarti** [comment]
Thank you @vincedevendra !
