### ISSUE TITLE
App doesn't receive push notifications if it's closed.

### ISSUE THREAD

**Issue by Bistaff** [patientslikeme/firebase_cloud_messenger#5]
Hi all,

How can I do to send and receive notifications also when app is closed?

Thanks in advance.

**Comment by vincedevendra** [comment]
Hi! Can you say a bit more about the problem you're having?

**Comment by Bistaff** [comment]
Hi,

I'm using this plugin in rails and I have a Ionic app. When I send the push from rails, it arrives on my ionic app only when the app is in background or foreground.

There is a way to receive push on my app also when is closed?

**Comment by vincedevendra** [comment]
I don't think I can be any help, unfortunately. If firebase_cloud_messenger is getting the message successfully up to Google, then it's done its job. There's no specific server-side settings that would cause the message not to be received when an app is closed. There is, I suspect, something more that needs to be done in your client app code.
